"""
core/schemas.py - Pydantic models for structured validation
Provides type-safe data models with automatic validation
"""
from pydantic import BaseModel, Field, validator
from typing import List, Optional

class Blueprint(BaseModel):
    """
    Project file blueprint generated by AI Architect.
    
    Automatically ensures:
    - Valid file extensions
    - Presence of main.py and requirements.txt
    - No library names mistaken as filenames
    """
    files: List[str] = Field(..., min_items=1, description="List of files to generate")
    architecture_notes: str = Field(default="", description="Architecture explanation")
    
    @validator('files')
    def validate_filenames(cls, v):
        """Ensure valid file extensions"""
        valid_extensions = ('.py', '.txt', '.md', '.json', '.yml', '.yaml', '.toml', '.cfg')
        
        for f in v:
            if not any(f.endswith(ext) for ext in valid_extensions):
                raise ValueError(f"Invalid file extension: {f}")
        
        return v
    
    @validator('files')
    def ensure_essentials(cls, v):
        """Ensure main.py and requirements.txt are present"""
        if 'main.py' not in v:
            v.insert(0, 'main.py')
        
        if 'requirements.txt' not in v:
            v.append('requirements.txt')
        
        return list(dict.fromkeys(v))  # Remove duplicates while preserving order

class CodeFile(BaseModel):
    """
    Generated code file with metadata.
    """
    filename: str
    content: str = Field(..., min_length=10, description="File content (minimum 10 chars)")
    language: str = "python"
    size_bytes: int = 0
    attempts: int = 1  # Number of generation attempts needed
    
    @validator('size_bytes', always=True)
    def calculate_size(cls, v, values):
        """Auto-calculate file size from content"""
        if 'content' in values:
            return len(values['content'])
        return 0
    
    class Config:
        # Allow arbitrary types for future extensibility
        arbitrary_types_allowed = True

class ProjectState(BaseModel):
    """
    Build state for crash recovery.
    Saved as .build_state.json in project directory.
    """
    phase: str = Field(..., description="Current build phase")
    blueprint: List[str] = Field(..., description="List of all files to generate")
    completed_files: List[str] = Field(default_factory=list, description="Already generated files")
    goal: str = Field(..., description="Project objective")
    timestamp: float = Field(..., description="Unix timestamp of last update")
    
    @validator('phase')
    def validate_phase(cls, v):
        """Ensure phase is valid"""
        valid_phases = [
            "blueprint_complete",
            "construction_in_progress",
            "construction_complete",
            "integration_complete",
            "testing_complete"
        ]
        
        if v not in valid_phases:
            raise ValueError(f"Invalid phase: {v}. Must be one of {valid_phases}")
        
        return v
    
    def is_expired(self, max_age_hours: int = 24) -> bool:
        """Check if state is too old"""
        import time
        age_hours = (time.time() - self.timestamp) / 3600
        return age_hours > max_age_hours
